# """PaperGPT configurations.yaml file."""

# this yaml file should contain all the underlying modules 
# implemented so far. It will allow users to select specific
# modules that they wish to run and also configure the input
# parameters based on their needs.

# the format of the module should be as follows
# Modules:
#     module_name:
#         UseModule: True / False (wether to use this module)
#         Timeout: # of minutes
#         UserParams: # user defined parameters provided by the developer
#             Param1: Param1-Value
#             Param2: Param2-Value
#             Param3: Param3-Value
#             Param4-List:
#                 - list-entry-1
#                 - list-entry-2
#                 - list-entry-3

modules:
    arvix:
        useModule: True
        timeout: 0.25
        userParams:
            title_keys:
                - Federated+Learning
                - FL
                - FL2
            abstract_keys:
                - Federated+Learning
                - FL3
                - FL4
            other_keys:
                - Federated+Learning
                - FL5
